language: java
jdk:
- oraclejdk8
env:
  global:
    - secure: jedqPDMvcKRFEde8TX4ERAhL8o56pZZr6SnGe2zwrWuD34P8fn4V40AuIchbpkys5QaORS7Jt49v53nObpb6dMT3f8Xp990iyrYpmybk39dBDDtdWu+jr4dy3P9YFtHX83D2Ub6Rvu1EPtC3iGgkFHhy0IATD1ty0GLGUJ9l+AZ8kTgohsBWmUctyEXPGb/NiMaCm1ay8jb2rDwqWaFmufttesN9BI34bQOZprOQfq59+tuYxZp6QiuOg8V8XtFA4VuzIKxtwVgcW7yiGaiQDeMXYDo9xsRGZzN0B5ixQKy7x7U3ifXW8uXTn/UAN8pU6NKc9wWk7+dxY2/9StHe5UpQf1BzxQ4y6AsX/ghn1n7yZRz3lw3d/Xz+spu1MkHv8tmauWGt+EO0EH1k02655FjNq3mrzsnuGllqMXIcS5EohDjRe1MM68t5n3RGmKkPBE1jTqbW2Ot8XsgkZ0H9PNY6DYEq/MvgIOyTAnzyqUdlqy8FtTaMy0qAAOFJbSZPo48JbieurCfwC1xuch/Xe0AHtlOcuAH3JvJvhD8JdhJIXfXRLQLYpNOjxE6h+17fi1x6L1cZG1jcC49GbhzbBmelu8A3G/sycsTWflKgCG5D35XalU5te12ZY+2g6s1A7tLJ0cO6vuyfu6GRmpIVfFpag61sAUAUKVSDKrwzWes=
notifications:
  slack: dptinfo-utln:s9uHkzBSlZjTfpqfinA2K7db
before_install:
  - wget http://mirrors.ircam.fr/pub/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
  - tar zxvf apache-maven-3.3.9-bin.tar.gz
  - chmod +x apache-maven-3.3.9/bin/mvn
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r
before_script:
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$PWD/apache-maven-3.3.9/bin:${PATH}
  - hash -r
script:
  - mvn org.jacoco:jacoco-maven-plugin:prepare-agent verify
  - mvn verify sonar:sonar -Dsonar.login=$SONAR_TOKEN -Dsonar.host.url=https://sonar.lsis.univ-tln.fr
branches:
    only:
        - master
        - development
